### ISSUE TITLE
运行train_lora_lion.py文件的相关错误

### ISSUE THREAD

**Issue by jojodan514** [LiuHC0428/LAW-GPT#14]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 23.70 GiB total capacity; 5.63 GiB already allocated; 80.38 MiB free; 5.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

修改了max_split_size_mb还是不行

**Comment by LiuHC0428** [comment]
请问batch_size是多少，同时显卡具体情况是什么样子？

**Comment by jojodan514** [comment]
这个问题我已经解决了，现在的问题是local_rank设置为0，会报错：ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [0], output_device 0, and module parameters {device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4)}.

**Comment by LiuHC0428** [comment]
local_rank默认就行，不需要设置，采用的是模型并行，local_rank是数据并行留的接口

**Comment by LiuHC0428** [comment]
好的感谢，训练过程中将验证过程去除了~

**Comment by jojodan514** [comment]
运行还有点问题，会报错：RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by LiuHC0428** [comment]
有可能是batch size太大，或者CUDA版本和torch不匹配，也有embedding维度不匹配的问题，需要打印具体参数

**Comment by jojodan514** [comment]
batch size我设置为2和1都不行，torch是1.3.1，cuda是11.7，数据集采用的是CrimeKgAssitant清洗后_52k，embedding维度这个我倒不清楚怎么看

**Comment by LiuHC0428** [comment]
请提供具体的报错信息以及配置信息

**Comment by jojodan514** [comment]
[log.txt](https://github.com/LiuHC0428/LAW-GPT/files/11420419/log.txt)
配置和requirement一样

**Comment by jojodan514** [comment]
能否加个qq：695686104，还是有点问题，想和您讨论一下

**Comment by hycao** [comment]
@jojodan514 麻烦问下，这个训练需要如何训练。

我这边已经下载了数据集，但是还是有点疑惑？

训练时，是在已经有的法律法规模型上继续训练呢，还是可以重新训练
